/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': '#2c2c2f',
        'surface-container-lowest': '#000000',
        'surface': '#0e0e10',
        'primary-fixed': '#c284ff',
        'on-surface-variant': '#adaaad',
        'secondary-container': '#3323cc',
        'on-surface': '#f9f5f8',
        'secondary-fixed-dim': '#c0bdff',
        'on-secondary-container': '#cecbff',
        'on-tertiary-container': '#004b58',
        'on-background': '#f9f5f8',
        'on-tertiary-fixed-variant': '#005564',
        'on-primary': '#47007c',
        'primary-fixed-dim': '#b971ff',
        'surface-tint': '#cc97ff',
        'tertiary': '#8ce7ff',
        'surface-container-highest': '#262528',
        'on-tertiary-fixed': '#003640',
        'tertiary-fixed-dim': '#40ceed',
        'error-container': '#a70138',
        'surface-dim': '#0e0e10',
        'inverse-primary': '#842cd3',
        'secondary-fixed': '#cfcdff',
        'secondary': '#9492ff',
        'error': '#ff6e84',
        'on-secondary-fixed': '#2000b0',
        'primary-dim': '#9c48ea',
        'on-secondary': '#120076',
        'on-error-container': '#ffb2b9',
        'on-primary-container': '#360061',
        'on-error': '#490013',
        'on-secondary-fixed-variant': '#3e32d5',
        'inverse-surface': '#fcf8fb',
        'primary': '#cc97ff',
        'outline': '#767577',
        'surface-container': '#19191c',
        'background': '#0e0e10',
        'primary-container': '#c284ff',
        'surface-container-high': '#1f1f22',
        'error-dim': '#d73357',
        'surface-variant': '#262528',
        'on-primary-fixed': '#000000',
        'surface-container-low': '#131315',
        'on-primary-fixed-variant': '#430076',
        'tertiary-dim': '#40ceed',
        'inverse-on-surface': '#565457',
        'tertiary-fixed': '#53ddfc',
        'secondary-dim': '#645efb',
        'tertiary-container': '#53ddfc',
        'outline-variant': '#48474a',
        'on-tertiary': '#005464',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
};
